### ISSUE TITLE
codesandboxer-fs badly resolving filePaths

### ISSUE THREAD

**Issue by Noviny** [Noviny/codesandboxer#17]
The way `codesandboxer-fs` is converting relative paths extract from files to absolute paths of that file's location is using some shonky regex (see its `relToAbs` function). If you have recursive references, it goes to heck.

Example:

You have a file at `src/myPackage/src` and something in `src/myPackage/file.js` imports `./src`, it will resolve the absolute path as `src/src/myPackage/src`.

**Comment by Noviny** [comment]
Also see trying to resolve `atlaskit/packages/core/button/src/components/Button.js` which has some weirdness to it.

**Comment by Noviny** [comment]
Likely to end up adding [resolve-from](https://github.com/sindresorhus/resolve-from) for our `codesandboxer-fs`-specific resolutions

**Comment by Noviny** [comment]
Resolved as of 0.2.0

**Comment by lukebatchelor** [comment]
Hmmm.. Just installed vs-codesandboxer 0.2.2 and am still getting the error

```
an error was thrown Error: Cannot find module '/Users/lbatchelor/src/atlaskit-mk-2/packages/core/badge/src/atlaskit-mk-2/packages/core/badge/src/Badge'
```

The extensions node_modules has codesandboxer-fs version 0.2.0 and codesandboxer 0.3.0
